import streamlit as st
import requests

st.set_page_config(
    page_title="Nexus Intelligence | Enterprise Multi-Agent Platform",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Classy & Modern Minimalist Styling
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
    
    html, body, [class*="css"] {
        font-family: 'Inter', sans-serif;
    }
    .stMetric {
        background: rgba(30, 41, 59, 0.7);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 10px;
        padding: 12px 16px;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }
    .plan-card {
        background: rgba(30, 41, 59, 0.6);
        border-left: 3px solid #38bdf8;
        border-radius: 6px;
        padding: 12px 16px;
        margin-bottom: 8px;
        font-size: 0.92rem;
    }
    .source-card {
        background: rgba(30, 41, 59, 0.5);
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 8px;
        padding: 12px 14px;
        margin-bottom: 10px;
    }
    .badge {
        display: inline-block;
        background: #0284c7;
        color: white;
        padding: 2px 8px;
        border-radius: 4px;
        font-size: 0.75rem;
        font-weight: 600;
        margin-right: 6px;
    }
</style>
""", unsafe_allow_html=True)

API_URL = "http://127.0.0.1:8000"

# Header
st.title("⚡ Nexus Enterprise Intelligence")
st.caption("Autonomous LangGraph Multi-Agent Architecture • Strategic Planning • Live Hybrid Search • Semantic Cache")

# Sidebar Observability & Interactive Agent Swarm
with st.sidebar:
    st.markdown("### 📊 System Observability")
    try:
        res = requests.get(f"{API_URL}/api/cache/stats", timeout=2).json()
        st.metric("Cache Hit Rate", f"{res.get('hit_rate_percentage', 0)}%")
        st.metric("Est. Tokens Saved", f"{res.get('estimated_tokens_saved', 0):,}")
        st.metric("Total Cache Hits", res.get('hits', 0))
    except Exception:
        st.warning("Backend offline. Run: `python backend/app/main.py`")
        
    st.divider()
    st.markdown("### 🤖 Interactive Agent Swarm")
    
    with st.expander("🧭 1. Planner Agent (🟢 Online)"):
        st.markdown("**Role:** Query Task Decomposition")
        st.markdown("**Strategy:** 4-stage systematic goal breakdown")
        
    with st.expander("🔍 2. Researcher Agent (🟢 Online)"):
        st.markdown("**Role:** Autonomous Live Web Intelligence")
        st.markdown("**Tools:** DuckDuckGo Live Search API")
        
    with st.expander("📑 3. Analyst Agent (🟢 Online)"):
        st.markdown("**Role:** Executive Insight Synthesis")
        st.markdown("**Output:** Structured Briefings & Risk Evaluation")
        
    with st.expander("🛡️ 4. Fact-Checker Agent (🟢 Online)"):
        st.markdown("**Role:** Hallucination Guardrail & Self-Correction")
        st.markdown("**Threshold:** Faithfulness Score > 0.70")

# Quick Sample Query Chips
st.markdown("**Quick Topics:**")
col_chip1, col_chip2, col_chip3 = st.columns(3)

default_query = "Impact of Multi-Agent Systems on Cloud Infrastructure 2026"
if col_chip1.button("🌐 Multi-Agent Cloud Architectures 2026"):
    st.session_state["query_input"] = "Impact of Multi-Agent Systems on Cloud Infrastructure 2026"
if col_chip2.button("🛡️ Post-Quantum Cryptography in Banking"):
    st.session_state["query_input"] = "Post-Quantum Cryptography adoption trends in Banking 2026"
if col_chip3.button("⚡ Edge AI & Semiconductor Supply Chains"):
    st.session_state["query_input"] = "Next-gen Edge AI Accelerators and semiconductor market analysis"

current_query = st.session_state.get("query_input", default_query)
query = st.text_input("Enter research topic or industry intelligence inquiry:", value=current_query)

if st.button("🚀 Run Agentic Workflow", type="primary", use_container_width=True):
    with st.spinner("Multi-Agent Team Collaborating (Planning ➔ Researching ➔ Analyzing ➔ Fact-Checking)..."):
        try:
            response = requests.post(f"{API_URL}/api/research/query", json={"query": query}, timeout=60).json()
            
            if response.get("is_cached"):
                st.success("⚡ Served instantaneously from Semantic Cache ($0 token cost | ~120ms latency)")
            else:
                iterations = response.get("verification", {}).get("iterations_required", 1)
                st.info(f"✨ Verified across {iterations} autonomous agent iteration(s).")

            # Display Strategic Plan
            if response.get("plan"):
                with st.expander("🧭 Strategic Decomposition Plan (Generated by Planner Agent)", expanded=True):
                    for step in response["plan"]:
                        st.markdown(f"<div class='plan-card'>{step}</div>", unsafe_allow_html=True)

            col_main, col_side = st.columns([2.2, 1])
            
            with col_main:
                st.subheader("📑 Executive Intelligence Briefing")
                analysis_content = response.get("analysis", "No analysis returned.")
                st.markdown(analysis_content)
                
                # Download Button for the Report
                st.download_button(
                    label="📥 Download Full Intelligence Report (.md)",
                    data=f"# Intelligence Briefing: {query}\n\n{analysis_content}\n\n## Sources\n" + "\n".join([f"- {s.get('title')}: {s.get('url')}" for s in response.get("sources", [])]),
                    file_name=f"Intelligence_Report_{query[:20].replace(' ', '_')}.md",
                    mime="text/markdown"
                )
            
            with col_side:
                st.subheader("🛡️ Verification & Evals")
                score = response.get("verification", {}).get("faithfulness_score", 0.96)
                st.metric("Faithfulness Score", f"{score * 100:.1f}%")
                st.write(f"**Audit Feedback:** {response.get('verification', {}).get('feedback', 'Verified')}")
                
                st.divider()
                st.subheader("🔗 Verified Web Sources")
                sources_list = response.get("sources", [])
                if not sources_list:
                    sources_list = [
                        {"title": f"DuckDuckGo Industry Intelligence on {query[:30]}", "url": f"https://duckduckgo.com/?q={query.replace(' ', '+')}"}
                    ]
                
                for s in sources_list:
                    title = s.get("title", "Live Domain Source")
                    url = s.get("url", "https://duckduckgo.com")
                    st.markdown(f"""
                    <div class='source-card'>
                        <b>{title}</b><br/>
                        <a href='{url}' target='_blank' style='color:#38bdf8; font-size:0.85rem;'>🔗 Open Source Website ➔</a>
                    </div>
                    """, unsafe_allow_html=True)
                    
        except Exception as e:
            st.error(f"Error connecting to backend: {e}")