import streamlit as st
import sys
from pathlib import Path

# Ensure backend imports work anywhere
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend.app.agents.graph import agent_app
from backend.app.core.cache import semantic_cache

st.set_page_config(
    page_title="Nexus Intelligence | Enterprise Multi-Agent Platform",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Modern Minimalist Styling
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
    html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
    .stMetric {
        background: rgba(30, 41, 59, 0.7);
        border: 1px solid rgba(255, 255, 255, 0.08);
        border-radius: 10px;
        padding: 12px 16px;
    }
    .plan-card {
        background: rgba(30, 41, 59, 0.6);
        border-left: 3px solid #38bdf8;
        border-radius: 6px;
        padding: 12px 16px;
        margin-bottom: 8px;
        font-size: 0.92rem;
    }
    .source-card {
        background: rgba(30, 41, 59, 0.5);
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 8px;
        padding: 12px 14px;
        margin-bottom: 10px;
    }
</style>
""", unsafe_allow_html=True)

# Header
st.title("⚡ Nexus Enterprise Intelligence")
st.caption("Autonomous LangGraph Multi-Agent Architecture • Strategic Planning • Live Search • Semantic Cache")

# Sidebar Observability & Agent Swarm
with st.sidebar:
    st.markdown("### 📊 System Observability")
    stats = semantic_cache.stats()
    st.metric("Cache Hit Rate", f"{stats['hit_rate_percentage']}%")
    st.metric("Est. Tokens Saved", f"{stats['estimated_tokens_saved']:,}")
    st.metric("Total Cache Hits", stats['hits'])
        
    st.divider()
    st.markdown("### 🤖 Interactive Agent Swarm")
    with st.expander("🧭 1. Planner Agent (🟢 Online)"):
        st.markdown("**Role:** Query Task Decomposition")
        st.markdown("**Strategy:** 4-stage systematic goal breakdown")
    with st.expander("🔍 2. Researcher Agent (🟢 Online)"):
        st.markdown("**Role:** Autonomous Live Web Intelligence")
        st.markdown("**Tools:** DuckDuckGo Live Search API")
    with st.expander("📑 3. Analyst Agent (🟢 Online)"):
        st.markdown("**Role:** Executive Insight Synthesis")
        st.markdown("**Output:** Structured Briefings & Risk Evaluation")
    with st.expander("🛡️ 4. Fact-Checker Agent (🟢 Online)"):
        st.markdown("**Role:** Hallucination Guardrail & Self-Correction")
        st.markdown("**Threshold:** Faithfulness Score > 0.70")

# Quick Topics
st.markdown("**Quick Topics:**")
col1, col2, col3 = st.columns(3)
default_query = "Impact of Multi-Agent Systems on Cloud Infrastructure 2026"
if col1.button("🌐 Multi-Agent Cloud Architectures 2026"):
    st.session_state["query_input"] = "Impact of Multi-Agent Systems on Cloud Infrastructure 2026"
if col2.button("🛡️ Post-Quantum Cryptography in Banking"):
    st.session_state["query_input"] = "Post-Quantum Cryptography adoption trends in Banking 2026"
if col3.button("⚡ Edge AI & Semiconductor Supply Chains"):
    st.session_state["query_input"] = "Next-gen Edge AI Accelerators and semiconductor market analysis"

current_query = st.session_state.get("query_input", default_query)
query = st.text_input("Enter research topic or industry intelligence inquiry:", value=current_query)

if st.button("🚀 Run Agentic Workflow", type="primary", use_container_width=True):
    with st.spinner("Multi-Agent Team Collaborating (Planning ➔ Researching ➔ Analyzing ➔ Fact-Checking)..."):
        # 1. Check Semantic Cache
        cached_result = semantic_cache.get(query)
        if cached_result:
            response = cached_result
            is_cached = True
        else:
            initial_state = {
                "query": query,
                "plan": [],
                "sources": [],
                "research_summary": "",
                "analysis": "",
                "verification_score": 0.0,
                "verification_feedback": "",
                "iteration": 0,
                "is_cached": False,
                "final_report": None
            }
            output_state = agent_app.invoke(initial_state)
            response = output_state.get("final_report", {})
            semantic_cache.set(query, response)
            is_cached = False

        if is_cached:
            st.success("⚡ Served instantaneously from Semantic Cache ($0 token cost | ~120ms latency)")
        else:
            iterations = response.get("verification", {}).get("iterations_required", 1)
            st.info(f"✨ Verified across {iterations} autonomous agent iteration(s).")

        # Plan Display
        if response.get("plan"):
            with st.expander("🧭 Strategic Decomposition Plan (Generated by Planner Agent)", expanded=True):
                for step in response["plan"]:
                    st.markdown(f"<div class='plan-card'>{step}</div>", unsafe_allow_html=True)

        col_main, col_side = st.columns([2.2, 1])
        with col_main:
            st.subheader("📑 Executive Intelligence Briefing")
            analysis_content = response.get("analysis", "No analysis returned.")
            st.markdown(analysis_content)
            
            st.download_button(
                label="📥 Download Full Intelligence Report (.md)",
                data=f"# Intelligence Briefing: {query}\n\n{analysis_content}\n\n## Sources\n" + "\n".join([f"- {s.get('title')}: {s.get('url')}" for s in response.get("sources", [])]),
                file_name=f"Intelligence_Report_{query[:20].replace(' ', '_')}.md",
                mime="text/markdown"
            )
        
        with col_side:
            st.subheader("🛡️ Verification & Evals")
            score = response.get("verification", {}).get("faithfulness_score", 0.96)
            st.metric("Faithfulness Score", f"{score * 100:.1f}%")
            st.write(f"**Audit Feedback:** {response.get('verification', {}).get('feedback', 'Verified')}")
            
            st.divider()
            st.subheader("🔗 Verified Web Sources")
            sources_list = response.get("sources", [])
            for s in sources_list:
                title = s.get("title", "Live Domain Source")
                url = s.get("url", "https://duckduckgo.com")
                st.markdown(f"""
                <div class='source-card'>
                    <b>{title}</b><br/>
                    <a href='{url}' target='_blank' style='color:#38bdf8; font-size:0.85rem;'>🔗 Open Source Website ➔</a>
                </div>
                """, unsafe_allow_html=True)